### ISSUE TITLE
Plugin doesn't load all the albums

### ISSUE THREAD

**Issue by Welvin** [dwainm/Facebook-Album-Sync#27]
I posted the same question to the support section of the plugin but thought of posting it here. I would appreciate any resolution and I'll promise to donate a little amount in return.

http://wordpress.org/support/topic/not-all-albums-are-loading?replies=1#post-5396238

Thank you very much.

Best regards,

**Comment by dwainm** [comment]
@Welvin this has been fixed in the release branch which will be out shortly.

https://github.com/dwainm/Facebook-Album-Sync/tree/release-1
