### ISSUE TITLE
Multiple times the same album displayed

### ISSUE THREAD

**Issue by bkeetman** [dwainm/Facebook-Album-Sync#32]
Seems like the latest version for me shows the samen albums multiple times.

Example:
http://www.deducdalf.nl/foto-album/

![de_ducdalf](https://cloud.githubusercontent.com/assets/800207/3982496/514edbcc-2877-11e4-9f69-ce28472ee6a5.png)

![de_ducdalf](https://cloud.githubusercontent.com/assets/800207/3982512/6ab02206-2877-11e4-96d7-45febe9fdf14.png)

**Comment by dwainm** [comment]
This issue has been fixed in the release branch:
https://github.com/dwainm/Facebook-Album-Sync/tree/release-1
